# -*- coding: utf-8 -*-
"""Missing_Value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQcJgo7IG24WySbmXwKx8S-zCZ_wU8KO
"""



"""**Handling Missing Values:**

Drop Columns: High Percentage of Missing values.

Imputation: Mean/Median/Mode - Replace missing values with mean, median, modeof the respective column.

Forward/ Backward Fill: Use previous or next row to fill missing values.

Interpolation: Linear- Fill values using linear interpolation between existing values.
"""

import pandas as pd

data = pd.read_csv("/content/employees.csv")

bool_series = pd.isnull(data["Gender"])

data[bool_series]

bool_series1 = pd.notnull(data["Gender"])
data[bool_series1]

data.isnull().sum()

data['First Name'].fillna('Unknown', inplace=True)

data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)

data['Senior Management'].fillna(data['Senior Management'].mode()[0], inplace=True)

data['Team'].fillna('Unknown Team', inplace = True)

data.head()

data.shape

data.isnull().sum()

